services:
  angular-app:
    container_name: elearningcontainer
    build: .
    ports:
      - "8082:80"
  mysql:
    image: "mysql:latest"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elearning
      MYSQL_PASSWORD: root
