# Supprimez la ligne `version: "3"` (obsolète)

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar  # Ajouté
      - SONARQUBE_JDBC_PASSWORD=sonar  # Ajouté
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_plugins:/opt/sonarqube/lib/common  # Correction du chemin
    depends_on:
      - db
    networks:
      - sonar

  db:
    image: postgres:13
    networks:
      - sonar
    environment:
      - POSTGRES_USER=sonar  # ✅ Supprimé l'espace
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar  # Ajouté pour créer la base
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=2wS3MB43gmvattFsQ95KaEsTNax_2ip66Kfu5EHeqCYWKL3ry  # ✅ Token direct
    command:
      - "http"
      - "9000"  # Tunnel vers SonarQube
    ports:
      - "4040:4040"
    networks:
      - sonar

networks:
  sonar:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_plugins:
  postgresql:
  postgresql_data:
